# Just an example. Please create one and have it alongside your JAR file.
dhis2-to-esavi:
  dhis2:
    base-url: https://example.com/dhis2/api
    username: admin
    password: district
    esavi-program-stage-id: lSpdre0srBn
  fhir:
    server-url: https://example.com/fhir
