# Just an example. Please create one and have it alongside your JAR file.
dhis2-to-esavi:
  dhis2:
    base-url: https://example.com/dhis
    username: admin
    password: district
  fhir:
    server-url: https://example.com/fhir
